using System.Text.Json.Nodes;
using Fireflies.GraphQL.Client.Generator.Schema;
using GraphQLParser.AST;
using GraphQLParser.Visitors;

namespace Fireflies.GraphQL.Client.Generator;

public class ClientGenerator : ASTVisitor<GraphQLGeneratorContext> {
    private readonly string _clientName;
    private readonly GeneratorSettings _generatorSettings;
    private readonly GraphQLDocument _graphQLDocument;

    private readonly GraphQLRootGeneratorContext _rootContext;

    public ClientGenerator(string clientName, JsonNode schema, GeneratorSettings generatorSettings, GraphQLDocument graphQLDocument) {
        _clientName = clientName;
        _generatorSettings = generatorSettings;
        _graphQLDocument = graphQLDocument;
        _rootContext = new GraphQLRootGeneratorContext(schema);
    }

    public string Source => _rootContext.Source + "\r\n" + "#pragma warning restore CS8618 // Data objects are populated by JSON";

    public async Task Generate() {
        var typeBuilder = _rootContext.GetRawTypeBuilder();
        typeBuilder.AppendLine("// <auto-generated/>");
        typeBuilder.AppendLine();
        typeBuilder.AppendLine("#nullable enable");
        typeBuilder.AppendLine();
        typeBuilder.AppendLine("using System.Text;");
        typeBuilder.AppendLine("using System.Text.Json;");
        typeBuilder.AppendLine("using System.Text.Json.Nodes;");
        typeBuilder.AppendLine("using System.Text.Json.Serialization;");

        typeBuilder.AppendLine();
        typeBuilder.AppendLine("#pragma warning disable CS8618 // Data objects are populated by JSON");
        typeBuilder.AppendLine();

        typeBuilder.AppendLine($"namespace {_generatorSettings.Namespace}.{_clientName};");

        GenerateTypes();

        var clientBuilder = _rootContext.GetClientBuilder(_clientName);

        var context = new GraphQLGeneratorContext(_rootContext, _graphQLDocument, new FragmentAccessor(_graphQLDocument));

        foreach(var operationDefinition in _graphQLDocument.Definitions.OfType<GraphQLOperationDefinition>()) {
            await clientBuilder.AddOperation(operationDefinition, context);
        }

        await clientBuilder.Build();

        var configBuilder = _rootContext.GetRawTypeBuilder();
        configBuilder.AppendLine($"public class {_clientName}ClientConfig {{");
        configBuilder.AppendLine("\tpublic Action<HttpBuilder>? ConfigureHttp { get; set; }");
        configBuilder.AppendLine("\tpublic Action<WebSocketBuilder>? ConfigureWebSocket { get; set; }");
        configBuilder.AppendLine("}");

        if(_generatorSettings.ServiceCollection) {
            var serviceCollectionBuilder = _rootContext.GetRawTypeBuilder();
            serviceCollectionBuilder.AppendLine("public static class IServiceCollectionExtensions {");
            serviceCollectionBuilder.AppendLine($"\tpublic static IServiceCollection Add{_clientName}Client(this IServiceCollection services, Action<{_clientName}ClientConfig> configuration) {{");
            serviceCollectionBuilder.AppendLine($"\t\tservices.AddTransient<I{_clientName}Client, {_clientName}Client>();");
            serviceCollectionBuilder.AppendLine();
            serviceCollectionBuilder.AppendLine($"\t\tvar config = new {_clientName}ClientConfig();");
            serviceCollectionBuilder.AppendLine("\t\tconfiguration(config);");
            serviceCollectionBuilder.AppendLine("\t\tservices.AddSingleton(config);");
            serviceCollectionBuilder.AppendLine("\t\tservices.AddSingleton<IGraphQLGlobalContext, GraphQLGlobalContext>();");
            serviceCollectionBuilder.AppendLine();
            serviceCollectionBuilder.AppendLine("\t\treturn services;");
            serviceCollectionBuilder.AppendLine("\t}");
            serviceCollectionBuilder.AppendLine("}");

            serviceCollectionBuilder.AppendLine();
        }
    }

    private void GenerateTypes() {
        foreach(var schemaType in _rootContext.SchemaTypes.Values) {
            switch(schemaType.Kind) {
                case SchemaTypeKind.ENUM:
                    GenerateEnum(schemaType);
                    break;
                case SchemaTypeKind.INPUT_OBJECT:
                    GenerateInputObject(schemaType);
                    break;
            }
        }
    }

    private string? GenerateInputObject(SchemaType schemaType) {
        var className = schemaType.Name;

        if(!_rootContext.ShouldGenerateType(className))
            return className;

        var typeBuilder = _rootContext.GetRawTypeBuilder();
        typeBuilder.AppendLine($"public class {className} {{");

        foreach(var field in schemaType.InputFields.Select(x => new { x.Type, x.Name }).Union(schemaType.Fields.Select(x => new { Type = x.Type, x.Name }))) {
            var fieldType = field.Type.GetOfType(_rootContext);
            if(fieldType.Kind is SchemaTypeKind.SCALAR or SchemaTypeKind.ENUM) {
                typeBuilder.AppendLine($"\tpublic {field.Type.GetNetType()} {field.Name.Capitalize()} {{ get; set; }}");
            } else {
                var subType = GenerateInputObject(field.Type.GetOfType(_rootContext));
                typeBuilder.AppendLine($"\tpublic {subType} {field.Name.Capitalize()} {{ get; set; }}");
            }
        }

        typeBuilder.AppendLine("}");

        return className;
    }

    private void GenerateEnum(SchemaType schemaType) {
        var typeBuilder = _rootContext.GetRawTypeBuilder();
        typeBuilder.AppendLine($"public enum {schemaType.Name} {{");
        foreach(var value in schemaType.EnumValues) {
            if(value.IsDeprecated)
                typeBuilder.AppendLine($"\t[{nameof(ObsoleteAttribute)}{(value.DeprecationReason != null ? $"({value.DeprecationReason})" : null)}]");
            typeBuilder.AppendLine($"\t{value.Name},");
        }

        typeBuilder.AppendLine("}");
    }
}